name: iblrig
channels:
  - defaults
dependencies:
  - python>=3.7.9,<3.8
  - pip>=20.3.1
  - setuptools>=51.0.0
  - wheel>=0.36.1
  - pip:
    - asn1crypto==0.24.0
    - colorlog
    - colorama==0.4.1
    - cython==0.29.6
    - globus-sdk==1.7.1
    - packaging==20.8
    - pybpod-api==1.8.2
    - pybpod-gui-api==1.8.2
    - pybpod-gui-plugin==1.8.2
    - pybpod-gui-plugin-emulator==0.1.5
    - pybpod-gui-plugin-rotaryencoder==0.1.4
    - pybpod-gui-plugin-session-history==1.4.2
    - pybpod-gui-plugin-soundcard==0.1.6
    - pybpod-gui-plugin-stmdiagram==1.0.0
    - pybpod-gui-plugin-timeline==1.0.1
    - pybpod-gui-plugin-trial-timeline==1.0.0
    - pybpod-gui-plugin-waveplayer==1.0
    - pyopenssl==19.0.0
    - pysocks==1.6.8
    - python-osc==1.7.0
    - sounddevice==0.3.13
    - pandas==1.1.5
