NAME: _iblrig_testlab_behavior_1
device_bpod:
  COM_BPOD: ''
  BPOD_TTL_TEST_DATE: ''
  BPOD_TTL_TEST_STATUS: ''
device_frame2ttl:
  COM_F2TTL: ''
  F2TTL_CALIBRATION_DATE: ''
  F2TTL_DARK_THRESH: ''
  F2TTL_HW_VERSION: ''
  F2TTL_LIGHT_THRESH: ''
device_rotary_encoder:
  COM_ROTARY_ENCODER: ''
device_screen:
  DISPLAY_IDX: 1
  SCREEN_FREQ_TARGET: 60
  SCREEN_FREQ_TEST_DATE: ''
  SCREEN_FREQ_TEST_STATUS: ''
  SCREEN_LUX_DATE: ''
  SCREEN_LUX_VALUE: ''
device_valve:
  WATER_CALIBRATION_DATE: ''
  WATER_CALIBRATION_OPEN_TIMES: ''
  WATER_CALIBRATION_RANGE: ''
  WATER_CALIBRATION_WEIGHT_PERDROP: ''
