name: CI

on:
  push:
    branches: [master, develop, rc]
  pull_request:
    branches: [master, develop, rc]

jobs:
  build_reqs:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      IBLRIG_REQS: iblrig_requirements_frozen.txt
      IBLLIB_REQS: ibllib_requirements_frozen.txt
    strategy:
      matrix:
        os: [ "windows-latest" ]
        python-version: ["3.8"]
    steps:
      - name: Clone iblrig repo
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: iblrig
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: flake8
        shell: bash -l {0}
        run: |
          pip install flake8 --quiet
          python -m flake8

      - name: iblrig installation
        shell: pwsh -l {0}
        run: |
          echo "------ start info ------"
          conda info
          conda env list
          python --version
          echo "------ end info ------"
          pip install --editable .
          python setup_pybpod.py
          cd Bonsai
          powershell.exe .\install.ps1
          cd ..\..
          conda create --name ibllib python=3.8 --yes
          conda activate ibllib
          pip install ibllib
          python -c "from one.api import ONE; ONE(base_url='https://test.alyx.internationalbrainlab.org', username='test_user', password='TapetesBloc18', silent=True)"

      - name: iblrig unit tests
        shell: pwsh -l {0}
        run: |
          echo "------ start info ------"
          conda info
          conda env list
          python --version
          echo "------ end info ------"
          python -m unittest test_iblrig/test_adaptive.py
          python -m unittest test_iblrig/test_alyx.py
          python -m unittest test_iblrig/test_ibllib_imports.py
          python -m unittest test_iblrig/test_params.py 
          python -m unittest test_iblrig/test_path_helper.py
          python -m unittest test_iblrig/test_pybpod_config.py
          python -m unittest test_iblrig/test_scripts.py
          python -m unittest test_iblrig/test_start_pybpod.py
          python -m unittest test_iblrig/test_task.py
          # python -m unittest discover

      - name: Generate requirements_frozen.txt
        shell: pwsh -l {0}
        run: |
          echo "------ start info ------"
          conda info
          conda env list
          python --version
          echo "------ end info ------"
          pip freeze > iblrig_requirements_frozen.txt
          conda activate ibllib
          pip freeze > ibllib_requirements_frozen.txt

      - name: Store frozen requirements as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: requirements_frozen
          path: |
            iblrig_requirements_frozen.txt
            ibllib_requirements_frozen.txt