name: CI

on:
  push:
    branches: [master, develop, rc, feature/7.0.0]
  pull_request:
    branches: [master, develop, rc]

jobs:
  build_reqs:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      IBLRIG_REQS: iblrig_requirements_frozen.txt
      IBLLIB_REQS: ibllib_requirements_frozen.txt
    strategy:
      matrix:
        os: [ "windows-latest" ]
        python-version: ["3.8"]
    steps:
      - name: Clone iblrig repo
        uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: iblrig
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Flake8
        shell: bash -l {0}
        run: |
          pip install flake8 --quiet
          python -m flake8

      - name: IBLRIG Installation
        shell: pwsh -l {0}
        run: |
          conda info
          conda list
          python --version
          pwd
          pip install --editable .
          python setup_pybpod.py
          cd Bonsai
          powershell.exe .\install.ps1
          cd ..
          conda create --name ibllib python==3.8.13 --yes
          conda activate ibllib
          pip install ibllib
          python -c "from one.api import ONE; ONE(password='international')"
          conda activate iblrig
          python -m unittest discover

      - name: Generate requirements_frozen.txt
        shell: pwsh -l {0}
        run: |
          conda activate iblrig
          pip freeze > "$IBLRIG_REQS"
          conda activate ibllib
          pip freeze > "$IBLLIB_REQS"

      - name: Store frozen requirements as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: requirements_frozen
          path: |
            iblrig_requirements_frozen.txt
            ibllib_requirements_frozen.txt