name: CI

on:
  push:
    branches: [master, develop, rc]
  pull_request:
    branches: [master, develop, rc]

jobs:
  build_reqs:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest"]
        python-version: ["3.8"]
    steps:
      - name: Checkout iblrig repo
        uses: actions/checkout@v3
        with:
          path: iblrig

      - name: Checkout iblpybpod repo
        uses: actions/checkout@v3
        with:
          repository: int-brain-lab/iblpybpod
          path: iblpybpod

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: flake8
        shell: pwsh -l {0}
        run: |
          pwd
          ls
          pip install flake8 --quiet
          cd iblrig
          python -m flake8

      - name: iblrig installation
        shell: pwsh -l {0}
        run: |
          pwd
          ls
          pip install --editable iblrig
          pip install --editable iblpybpod
          cd iblrig
          python setup_pybpod.py
          cd Bonsai
          powershell.exe .\install.ps1

      - name: iblrig unit tests
        shell: pwsh -l {0}
        run: |
          pwd
          ls
          cd iblrig
          python -m unittest discover

      - name: Generate requirements_frozen.txt
        shell: pwsh -l {0}
        run: |
          pwd
          ls
          pip freeze > requirements_frozen.txt

      - name: Store frozen requirements as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: requirements_frozen
          path: |
            requirements_frozen.txt