name: CI

on:
  push:
    branches: [master, develop, rc, feature/iblpybpod_integrated]
  pull_request:
    branches: [master, develop, rc]

jobs:
  build_reqs:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "windows-latest" ]
        python-version: ["3.8", "3.9"]
    steps:
      - name: Clone iblrig repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: flake8
        shell: bash -l {0}
        run: |
          pip install flake8 --quiet
          python -m flake8

      - name: iblrig installation
        shell: pwsh -l {0}
        run: |
          python --version
          pip install --editable .
#          python setup_pybpod.py
          cd Bonsai
          powershell.exe .\install.ps1

#      - name: iblrig unit tests
#        shell: pwsh -l {0}
#        run: |
#          python --version
#          python -m unittest discover

      - name: Generate requirements_frozen.txt
        shell: pwsh -l {0}
        run: |
          python --version
          pip freeze > requirements_frozen.txt

      - name: Store frozen requirements as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: requirements_frozen
          path: |
            requirements_frozen.txt